image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - yarn dist:w64

test: off

version: build.0.0.{build}

artifacts:
- path: dist\*.exe
  name: GLaDOS-{build}


deploy:
- provider: GitHub
  auth_token:
    secure: 2D5Z8dThcF8po0aGOhhukBGFM3hZkIqhduh+DJjMaBDCbw9+b8CYkJL1OwPONe+h
