image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input
  - [Environment]::SetEnvironmentVariable("GH_TOKEN","80f99bcedd6f35fbeb3867e3369db67f76267200","User")

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - yarn dist:w64

test: off
