image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - yarn dist:w64

test: off

deploy:
- provider: GitHub
  auth_token:
    secure: Mz/7xFDiHKNYIthOboBDJpy5YdLKpLtI85TV0ltDfuCWkndRVAaTwVBowSGI+ben
